### PR TITLE
Height init update

### LINKED ISSUE #107: Height variable
EDIT: It looks like this will finally be addressed. We will add height initialisation and update code to the `KevinHallModel` class.

These functions will depend on factor means, which are already loaded into the model. They will also depend on three extra variables, which must be added to the `KevinHall.json` config, and passed into the model ctor via the model parser. These variables are:

* Slope = 0.11,
* StdDevMale = 0.04,
* StdDevFemale = 0.04.

I have began work in the `height` branch, where I have implemented some stub methods as comments, and the `compute_mean_weight_powers` method, which will be used in common code used by the init and update height methods.

Code for this is available in the attached. It is not explained very well what is going on, or the variable names/units, but we can worry about explaining that after.

[Height_Regression.cs.pdf](https://github.com/imperialCHEPI/healthgps/files/13325883/Height_Regression.cs.pdf)

NB: remove the `.pdf` extension -- GitHub won't let me upload without it.

***BELOW IS OUTDATED:***

>Height variable in risk factors. 
>We will have mean heights for M/F by age from the config json (in  progress).

>- [ ] Add `height` to `Person` struct (with code to access as a risk factor)
>- [ ] initialise (see Ali's code: `Height.cs`)
>- [ ] update (see Ali's code `Height.cs`)
>- [ ] Dynamic height model as an LMS mdoel in `DemographicsModule`

### PR DESCRIPTION
**Pull request by jamesturner246**
This PR adds the `initialise_height` and `update_height` methods, with supporting code, to the `KevinHallModel`.

A further reshuffling of `update_risk_factors` was required. It is ugly as hell, but the fragility of this horrible thing to update orderings makes it so. As a general rule to help follow, I have split the code mostly into newborn initialisation in the first half, and updating teenagers/adults in the second half. All three have different treatment.

Fixes #107 (finally)

### CODE REVIEW

**Comment by jamesturner246** [comment]
I don't understand this failure on `linux, ubuntu-22.04, gcc-default, true`...

**Review by dalonsoa — CHANGES_REQUESTED** [review]
You're right it looks pretty horrible. However, keeping aside major refactoring of the architecture of the code, I think it should be possible to "beautify" the code a bit by broken the `generate_risk_factors` method into smaller functions that take care of the individual use cases, that can be tested and explained appropriately (when the time comes). You might not have that much time now, but it might be necessary to keep the technical debt at bay, at least a bit.

**Review by alexdewar — APPROVED** [review]
A couple of comments, but otherwise LGTM.

File: src/HealthGPS/kevin_hall_model.cpp [hunk 1]
```diff
@@ -95,16 +100,48 @@ void KevinHallModel::update_risk_factors(RuntimeContext &context) {
...
-        if (!person.is_active()) {
+        // Ignore if inactive or not a newborn.
+        if (!person.is_active() || person.age != 0) {
+            continue;
+        }
+
+        double W_expected = expected.at(person.gender, "Weight"_id).at(0);
+        double W_mean = W_newborn_means.at(person.gender, 0);
+        double adjustment = W_expected - W_mean;
+        person.risk_factors.at("Weight"_id) -= adjustment;
```
[the remark this answers is not in the document]
Comment (jamesturner246) [reply src/HealthGPS/kevin_hall_model.cpp:123]: You're right, `adjustment` should be added not subtracted, though not flipped. If expected is higher, we want a positive adjustment, so `expected - mean`, and then ADD this to the risk factor. I'll change it.

File: src/HealthGPS/kevin_hall_model.cpp [hunk 2]
```diff
@@ -546,7 +594,8 @@ KevinHallAdjustmentTable KevinHallModel::compute_mean_weight(Population &populat
     sumcounts.emplace_row(core::Gender::female, std::unordered_map<int, SumCount>{});
     sumcounts.emplace_row(core::Gender::male, std::unordered_map<int, SumCount>{});
     for (const auto &person : population) {
-        if (!person.is_active()) {
+        bool age_mismatch = age.has_value() && person.age != age.value();
+        if (!person.is_active() || age_mismatch) {
             continue;
         }
```
[the remark this answers is not in the document]
Comment (jamesturner246) [reply src/HealthGPS/kevin_hall_model.cpp]: Done.

**Comment by jamesturner246** [comment]
Okay. Phew. I've had a crack at refactoring `update_risk_factors`: Separate functions for newborn and non-newborn, separate functions for computing adjustments, removed some duplication, separate functions for sending the adjustments to intervention, and a bit more tidying. It's still not amazing, but at least a bit easier to follow.

See the `// TODO: FOR REFACTORING:` note: a big chunk of code (the entire `initialise_newborn` can be totally removed and replaced with a general initialisation function once #266 is implemented, making it look way more tidy. 

Also kinda fixes #269.

File: src/HealthGPS/kevin_hall_model.cpp [hunk 3]
```diff
@@ -73,86 +73,156 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
+    // Initialise nutrient and energy intake and weight for newborns.
     for (auto &person : context.population()) {
-        // Ignore if inactive.
+        // Ignore if inactive or not newborn.
         if (!person.is_active()) {
             continue;
         }
+        if (person.age != 0) {
+            continue;
+        }
```
Comment (dalonsoa) [inline src/HealthGPS/kevin_hall_model.cpp:120]: Just to visually reduce the amount of lines of code, yet keeping things simple:
```suggestion
        if (!person.is_active() || (person.age != 0)) {
            continue;
        }
```

File: src/HealthGPS/kevin_hall_model.cpp [hunk 4]
```diff
@@ -73,86 +73,156 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
+    // Adjust newborn weight to match expected.
+    auto adjustments = compute_weight_adjustments(context.population(), 0);
+    for (auto &person : context.population()) {
+        // Ignore if inactive or not newborn.
+        if (!person.is_active()) {
+            continue;
         }
+        if (person.age != 0) {
+            continue;
+        }
```
Comment (dalonsoa) [inline src/HealthGPS/kevin_hall_model.cpp:148]: As above:
```suggestion
        if (!person.is_active() || (person.age != 0)) {
            continue;
        }
```

File: src/HealthGPS/kevin_hall_model.cpp [hunk 5]
```diff
@@ -73,86 +73,156 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
+
+    // Initialise height and other Kevin Hall state for newborns.
+    for (auto &person : context.population()) {
+        // Ignore if inactive or not newborn.
+        if (!person.is_active()) {
+            continue;
+        }
+        if (person.age != 0) {
+            continue;
+        }
```
Comment (dalonsoa) [inline src/HealthGPS/kevin_hall_model.cpp:167]: As above:
```suggestion
        if (!person.is_active() || (person.age != 0)) {
            continue;
        }
```

File: src/HealthGPS/kevin_hall_model.cpp [hunk 6]
```diff
@@ -73,86 +73,156 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
+
+    // Update nutrient and energy intake for non-newborns.
+    for (auto &person : context.population()) {
+        // Ignore if inactive or newborn.
+        if (!person.is_active()) {
+            continue;
         }
+        if (person.age == 0) {
+            continue;
+        }
```
Comment (dalonsoa) [inline src/HealthGPS/kevin_hall_model.cpp:185]: Guess what? 😄 
```suggestion
        if (!person.is_active() || (person.age == 0)) {
            continue;
        }
```

File: src/HealthGPS/kevin_hall_model.cpp [hunk 7]
```diff
@@ -73,86 +73,156 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
-                "Simulation out of sync, failed to receive a Kevin Hall adjustments message");
+    // Update weight for non-newborns.
+    for (auto &person : context.population()) {
+        // Ignore if inactive or newborn.
+        if (!person.is_active()) {
+            continue;
+        }
+        if (person.age == 0) {
+            continue;
         }
```
Comment (dalonsoa) [inline src/HealthGPS/kevin_hall_model.cpp:199]:
```suggestion
        if (!person.is_active() || (person.age == 0)) {
            continue;
        }
```

File: src/HealthGPS/kevin_hall_model.cpp [hunk 8]
```diff
@@ -73,86 +73,156 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
+    // Adjust weight and other Kevin Hall state for non-newborns.
     for (auto &person : context.population()) {
-        // Ignore if inactive.
+        // Ignore if inactive or newborn.
         if (!person.is_active()) {
             continue;
         }
+        if (person.age == 0) {
+            continue;
+        }
```
Comment (dalonsoa) [inline src/HealthGPS/kevin_hall_model.cpp:219]:
```suggestion
        if (!person.is_active() || (person.age == 0)) {
            continue;
        }
```

File: src/HealthGPS/kevin_hall_model.cpp [hunk 9]
```diff
@@ -162,29 +232,66 @@ void KevinHallModel::update_risk_factors(RuntimeContext &context) {
...
+        // Ignore if inactive or newborn or aged 19 and over.
         if (!person.is_active()) {
             continue;
         }
+        if (person.age == 0) {
+            continue;
+        }
+        if (person.age >= 19) {
+            continue;
+        }
```
Comment (dalonsoa) [inline src/HealthGPS/kevin_hall_model.cpp:249]:
```suggestion
        if (!person.is_active() || ((person.age == 0) || (person.age >= 19))) {
            continue;
        }
```

**Review by dalonsoa — APPROVED** [review]
Much better. The code is still complex, but the generate risk factors and update functions are more concise, clear and easier to follow :)

File: src/HealthGPS/kevin_hall_model.cpp (hunk 3 above)
Comment (jamesturner246) [reply src/HealthGPS/kevin_hall_model.cpp:120]: Ah, that was @alexdewar's suggestion. What's the tie breaker!?

Comment (jamesturner246) [reply src/HealthGPS/kevin_hall_model.cpp:120]: I tend to agree, though. All those `if`s are a bit verbose.

Comment (alexdewar) [reply src/HealthGPS/kevin_hall_model.cpp:120]: I only suggested it because I thought it needed to be `if (person.age.has_value() && person.age != 0)`. If the whole thing fits on one line now, then that's def better!

File: src/HealthGPS/kevin_hall_model.cpp [hunk 10]
```diff
@@ -73,118 +73,232 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
     }
+}
 
-    // Intervention scenario: recieve adjustments from baseline scenario.
-    else {
-        auto message = context.scenario().channel().try_receive(context.sync_timeout_millis());
-        if (!message.has_value()) {
-            throw core::HgpsException(
-                "Simulation out of sync, receive Kevin Hall adjustments message has timed out");
+void KevinHallModel::update_non_newborns(RuntimeContext &context) const {
```
[the remark this answers is not in the document]
Comment (alexdewar) [reply src/HealthGPS/kevin_hall_model.cpp:175]: Haha, `clang-tidy` has also clocked that this is complex :stuck_out_tongue:

File: src/HealthGPS/kevin_hall_model.cpp [hunk 11]
```diff
@@ -73,118 +73,232 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
+            continue;
+        }
 
-        compute_bmi(person);
+        double W_power_mean = W_power_means.at(person.gender, person.age);
+        update_height(person, W_power_mean);
+    }
+}
+
+KevinHallAdjustmentTable KevinHallModel::recieve_weight_adjustments(RuntimeContext &context) const {
```
Comment (alexdewar) [inline src/HealthGPS/kevin_hall_model.cpp:229]:
```suggestion
KevinHallAdjustmentTable KevinHallModel::receive_weight_adjustments(RuntimeContext &context) const {
```

Comment (alexdewar) [reply src/HealthGPS/kevin_hall_model.cpp:229]: This is better than before, but I still think this would be better if it returned a `std::optional<KevinHallAdjustmentTable>`, with `std::nullopt` indicating that something went wrong. Then the caller can treat this as an error

Comment (alexdewar) [reply src/HealthGPS/kevin_hall_model.cpp:229]: You know what, scratch that. I think this is a perfectly reasonably way of doing it

**Comment by jamesturner246** [comment]
Humph. Why all these builders doing strange stuff all of a sudden.

File: src/HealthGPS/kevin_hall_model.cpp [hunk 12]
```diff
@@ -73,118 +73,208 @@ void KevinHallModel::generate_risk_factors(RuntimeContext &context) {
...
     }
+}
 
-    // Intervention scenario: recieve adjustments from baseline scenario.
-    else {
-        auto message = context.scenario().channel().try_receive(context.sync_timeout_millis());
-        if (!message.has_value()) {
-            throw core::HgpsException(
-                "Simulation out of sync, receive Kevin Hall adjustments message has timed out");
+void KevinHallModel::update_non_newborns(RuntimeContext &context) const {
```
[the remark this answers is not in the document]
Comment (jamesturner246) [reply src/HealthGPS/kevin_hall_model.cpp:166]: No, you're complex...

**Review by alexdewar — APPROVED** [review]
LGTM!
