### PR TITLE
Fix YLL/Y:D/DALY and death

### LINKED ISSUE #442: Fix incorrect YLL and deaths in output
Right now, YLL is computed as `sum_over_dead_pop(years_lost_for_person * 100000) / n_alive`, but this doesn't seem like 'true' YLL. Surely it's divided by either `n_dead` or `n_dead + n_alive` or something.

If Health-GPS states that the output value is YLL, then it should be YLL, not some intermediate value.

We need to figure this out and output something sensible.

### PR DESCRIPTION
**Pull request by jamesturner246**
Fixes #442. 

The loops for mean and std have been tidied up, and are now 'opt-in', so no unwanted surprises in other columns that don't opt in.

YLL/YLD/DALY are now correctly computed by dividing by active *PLUS* deceased population.

Everything that should be an integer, such as deaths, migrations, weight classifications, is now an integer. Update your scripts accordingly.

### CODE REVIEW

**Comment by jamesturner246** [comment]
Don't they do CI on these Ubuntu builder images? :confused:

**Comment by jzhu20** [comment]
I don't really understand the codes for calculating standard deviation.
Lines 452-456 and 458-461: Do you substract individual value from group mean, then take squared to generate sum? I cannot locate this step. I get sqrt(sum/count) or sqrt(sum/(count+deaths)).

**Comment by jamesturner246** [comment]
Hi @jzhu20, this was done in a prior PR -- see lines 402-434.

**Review by jzhu20 — APPROVED** [review]

**Comment by jamesturner246** [comment]
Any thoughts @alexdewar?

**Comment by alexdewar** [comment]
Sorry for the slow reply! I'll take a look at this today

File: src/HealthGPS/analysis_module.cpp [hunk 1]
```diff
@@ -307,29 +307,28 @@ DALYsIndicator AnalysisModule::calculate_dalys(Population &population, unsigned
...
-        auto age = entity.age;
-        auto gender = entity.gender;
+    for (const auto &person : context.population()) {
+        auto age = person.age;
+        auto gender = person.gender;
 
-        if (!entity.is_active()) {
-            if (!entity.is_alive() && entity.time_of_death() == current_time) {
+        if (!person.is_active()) {
+            if (!person.is_alive() && person.time_of_death() == current_time) {
```
Comment (alexdewar) [inline src/HealthGPS/analysis_module.cpp:322]: Not relevant for this PR, but I feel like a `has_died()` method would be clearer than an `is_alive()` one.

File: src/HealthGPS/analysis_module.cpp [hunk 2]
```diff
@@ -487,9 +502,6 @@ void AnalysisModule::initialise_output_channels(RuntimeContext &context) {
         channels_.emplace_back("incidence_" + disease.code.to_string());
     }
 
-    channels_.emplace_back("disability_weight");
```
Comment (alexdewar) [inline src/HealthGPS/analysis_module.cpp:490]: Don't we need `disability_weight` anymore?

File: src/HealthGPS/analysis_module.cpp [hunk 3]
```diff
@@ -307,29 +307,28 @@ DALYsIndicator AnalysisModule::calculate_dalys(Population &population, unsigned
 // NOLINTBEGIN(readability-function-cognitive-complexity)
 void AnalysisModule::calculate_population_statistics(RuntimeContext &context,
                                                      DataSeries &series) const {
-    auto min_age = context.age_range().lower();
-    auto max_age = context.age_range().upper();
     if (series.size() > 0) {
         throw std::logic_error("This should be a new object!");
     }
```
Comment (alexdewar) [inline src/HealthGPS/analysis_module.cpp:312]: I think it would make more sense to return a new `DataSeries` object rather than modify an input argument.

But that's not something we need to do now.

**Review by alexdewar — APPROVED** [review]
I've eyeballed the code and it looks like it's doing the right thing. I've made some comments, none of which are actually about this PR :upside_down_face: 

That said, the `calculate_population_statistics()` method is a bit overcomplicated (we have to suppress a `clang-tidy` warning about this), so trying to keep track of everything that's going on made my head hurt. We should probably factor out some of the logic into separate functions at some point. Maybe we need a new issue for this?

**Comment by jamesturner246** [comment]
> That said, the `calculate_population_statistics()` method is a bit overcomplicated (we have to suppress a `clang-tidy` warning about this), so trying to keep track of everything that's going on made my head hurt. We should probably factor out some of the logic into separate functions at some point. Maybe we need a new issue for this?

Agree in principle, but I'm hesitant to invest any more time in this whilst knowing it will eventually be replaced by @TinyMarsh's work. Let's wait for the result of that before making any decisions.

File: src/HealthGPS/analysis_module.cpp (hunk 1 above)
Comment (jamesturner246) [reply src/HealthGPS/analysis_module.cpp:322]: Then you'd have `is_alive` and `has_died =  !is_alive` functions?

Unless you mean like:

```c++
bool Person::has_just_died(unsigned int current_time) {
    return !is_alive() && time_of_death() == current_time;
}
```
